name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*' # Trigger on pushes to tags starting with 'v'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/cschlaefli/feed-generator
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      
      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          push: true
          # Specify the target platforms for a multi‑arch build. BuildKit will
          # build each architecture separately and publish a manifest list.
          platforms: linux/amd64,linux/arm64
          # Pass through the platform arguments so the Dockerfile can use
          # TARGETPLATFORM and TARGETARCH for selecting the base image.
          build-args: |
            # These build args allow the Dockerfile to access TARGETPLATFORM and
            # TARGETARCH as provided by BuildKit when building each variant.
            TARGETPLATFORM
            TARGETARCH
          # Emit provenance and SBOMs for additional security and traceability.
          provenance: mode=max
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
